---
image: public.ecr.aws/sumologic/sumologic-kafka-push:latest
metricsPort: 8080
logLevel: warn

replicas: 1
dataType: logs
groupedSize: 30000
groupedDuration: '1s'
endpointsSecret: endpoints-logs

servicemonitor:
  labels: {}

kafka:
  bootstrapServers: localhost:9092
  topic: sumo-push-logs
  consumerGroup: sumopush-logs

autoscale:
  type: keda
  minReplicaCount: 1
  maxReplicaCount: 8
  keda:
    ratePerSecond: 9000
    cooldownPeriod: 1200
    pollingInterval: 30
    lagThreshold: '90'
    prometheus: http://thanos-query.{{ .Values.cluster }}-zaidan.svc:10902
  hpa:
    cpuThreshold: 90
