name: Release builds

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo $(git describe --tags --always))"
      - name: Print Tag
        run: echo "Running build for  ${{ steps.extract_tag.outputs.tag }}"
      - name: Login to ECR
        run: make login-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push docker image
        run: make publish-docker BUILD_TAG=${{ steps.extract_tag.outputs.tag }}